add reverse chronological order sorting
also add typing because I need them to add sorting

> Executing task: npm run start <

> reactive-material@0.0.0 start /home/kushal/src/html/myreactivematerialfirebase/ReactiveMaterial
> ng serve

chunk {main} main.js, main.js.map (main) 70.4 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 141 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.15 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 165 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 6.07 MB [initial] [rendered]
Date: 2020-07-18T16:20:26.579Z - Hash: 4f4dca31c10497118bb5 - Time: 24736ms
** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
: Compiled successfully.

Date: 2020-07-18T16:20:36.898Z - Hash: 4f4dca31c10497118bb5
5 unchanged chunks

Time: 1274ms
: Compiled successfully.

Date: 2020-07-18T16:24:14.319Z - Hash: ef3d7f50aacb6f4315e3
4 unchanged chunks
chunk {main} main.js, main.js.map (main) 70.6 kB [initial] [rendered]
Time: 1446ms
: Compiled successfully.

    ERROR in src/app/drupal-simple-article/drupal-simple-article.component.ts:20:43 - error TS7006: Parameter 'a' implicitly has an 'any' type.

    20       this.articles = response.data.sort((a, b) => (a.attributes.changed > b.attributes.changed) ? 1 : (b.attributes.changed > a.attributes.changed) ? -1 : 0);
                                                 ~
    src/app/drupal-simple-article/drupal-simple-article.component.ts:20:46 - error TS7006: Parameter 'b' implicitly has an 'any' type.

    20       this.articles = response.data.sort((a, b) => (a.attributes.changed > b.attributes.changed) ? 1 : (b.attributes.changed > a.attributes.changed) ? -1 : 0);
                                                    ~

Date: 2020-07-18T16:34:25.044Z - Hash: ef3d7f50aacb6f4315e3
5 unchanged chunks

Time: 958ms
: Compiled successfully.

    ERROR in src/app/drupal-simple-article/drupal-simple-article.component.ts:20:32 - error TS2339: Property 'data' does not exist on type 'DrupalSimpleArticle'.

    20       this.articles = response.data.sort((a, b) => (a.attributes.changed > b.attributes.changed) ? 1 : (b.attributes.changed > a.attributes.changed) ? -1 : 0);
                                      ~~~~
    src/app/drupal-simple-article/drupal-simple-article.component.ts:20:43 - error TS7006: Parameter 'a' implicitly has an 'any' type.

    20       this.articles = response.data.sort((a, b) => (a.attributes.changed > b.attributes.changed) ? 1 : (b.attributes.changed > a.attributes.changed) ? -1 : 0);
                                                 ~
    src/app/drupal-simple-article/drupal-simple-article.component.ts:20:46 - error TS7006: Parameter 'b' implicitly has an 'any' type.

    20       this.articles = response.data.sort((a, b) => (a.attributes.changed > b.attributes.changed) ? 1 : (b.attributes.changed > a.attributes.changed) ? -1 : 0);
                                                    ~

Date: 2020-07-18T16:37:42.342Z - Hash: ef3d7f50aacb6f4315e3
5 unchanged chunks

Time: 889ms
: Compiled successfully.

Date: 2020-07-18T16:38:14.446Z - Hash: 75ca142b983570bc3ec8
4 unchanged chunks
chunk {main} main.js, main.js.map (main) 70.6 kB [initial] [rendered]
Time: 1136ms
: Compiled successfully.

[kushal@ideapadflex-kushal ReactiveMaterial]$ ng generate class SimpleArticle
CREATE src/app/simple-article.spec.ts (183 bytes)
CREATE src/app/simple-article.ts (31 bytes)
[kushal@ideapadflex-kushal ReactiveMaterial]$ ng generate class DrupalSimpleArticle
CREATE src/app/drupal-simple-article.spec.ts (208 bytes)
CREATE src/app/drupal-simple-article.ts (37 bytes)
[kushal@ideapadflex-kushal ReactiveMaterial]$ ng generate class DrupalAttribute
CREATE src/app/drupal-attribute.spec.ts (191 bytes)
CREATE src/app/drupal-attribute.ts (33 bytes)
[kushal@ideapadflex-kushal ReactiveMaterial]$ ng generate class DrupalSimpleArticleData
CREATE src/app/drupal-simple-article-data.spec.ts (225 bytes)
CREATE src/app/drupal-simple-article-data.ts (41 bytes)
[kushal@ideapadflex-kushal ReactiveMaterial]$